### ISSUE TITLE
Can we add a clear pixel to CTP ?

### ISSUE THREAD

**Issue by byoung-joo** [NCAR/obs2mpas#14]
@ibanos90 has found an issue with using CTP information (https://github.com/byoung-joo/obs2model/pull/12) in her cloud verification. With this 10 km products, the missing NaN values mean several things, such as 1) clear pixel, 2) missing values within Full Disk area due to the resolution mismatch (usual 2km vs. 10km), and 3) missing values out of Full Disk area.

**Comment by byoung-joo** [comment]
From `OR_ABI-L2-CTPF` NetCDF file, the variable `DQF` contains the information on the clear pixel (flag **4**).
```
	byte DQF(y, x) ;
		DQF:_FillValue = -1b ;
		DQF:long_name = "ABI L2+ Cloud Top Pressure data quality flags" ;
		DQF:standard_name = "status_flag" ;
		DQF:_Unsigned = "true" ;
		DQF:valid_range = 0b, 6b ;
		DQF:units = "1" ;
		DQF:coordinates = "local_zenith_angle solar_zenith_angle t y x" ;
		DQF:grid_mapping = "goes_imager_projection" ;
		DQF:cell_methods = "local_zenith_angle: point solar_zenith_angle: point t: point area: point" ;
		DQF:flag_values = **0b**, 1b, 2b, 3b, **4b**, 5b, 6b ;
		DQF:flag_meanings = "**good_quality_qf** invalid_due_to_not_geolocated_qf invalid_due_to_LZA_threshold_exceeded_qf invalid_due_to_bad_or_missing_brightness_temp_data_qf **invalid_due_to_clear_or_probably_clear_sky_qf** invalid_due_to_unknown_cloud_type_qf invalid_due_to_nonconvergent_retrieval_qf" ;
```

But I need to think more... what will happen if in a give SO point, there are mixture of clear and cloudy pixels.... also what CTP value should be assigned for clear pixel.

**Comment by byoung-joo** [comment]
Made a small modification [feature/clear_CTP](https://github.com/byoung-joo/obs2model/compare/feature/clear_CTP?expand=1)

 * When the data is ingested, specify a `-777.0` value for quality flags with `4` (invalid_due_to_clear_or_probably_clear_sky_qf).
 * Add some logic in SO. No change is needed for the nearest neighbor method.
 * Build can be found in /glade/campaign/mmm/parc/bjung/pandac_common/CloudDirectInsert/obs2model_testdata/obs2model
 * Compared _old_ and _new_ files:
```
nccmp -dfS /glade/derecho/scratch/bjung/saca_new_mesh/obs_processing/convert.mpas_10kmL2/output_fixed/saca_obs.2018-04-15_00.00.00.nc /glade/campaign/mmm/parc/bjung/pandac_common/CloudDirectInsert/obs2model_testdata/obs2model/test_abi_read/newfile.nc_SO

DIFFER : VARIABLE : PRES_G16 : POSITION : [0,7] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,26] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,33] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,66] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,83] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,84] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,87] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,90] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,92] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,93] : VALUES : -777 <> -999
. . .
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,778970] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,781066] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,786575] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,788574] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,790076] : VALUES : -777 <> -999
DIFFER : VARIABLE : PRES_G16 : POSITION : [0,792210] : VALUES : -777 <> -999
Variable Group Count         Sum      AbsSum Min Max Range Mean StdDev
PRES_G16 /     60503 1.34317e+07 1.34317e+07 222 222     0  222      0
```

**Comment by byoung-joo** [comment]
@ibanos90,
Can you try your verification with /glade/derecho/scratch/bjung/saca_new_mesh/obs_processing/convert.mpas_10kmL2/output_fixed_clearCTP ?

**Comment by byoung-joo** [comment]
Other cloud products ( cloud top temperature, cloud top height, cloud top phase, ... ) should have the same issue. But should the clear information be added to those variables, too ? Are there any use-case ?

**Comment by ibanos90** [comment]
> Other cloud products ( cloud top temperature, cloud top height, cloud top phase, ... ) should have the same issue. But should the clear information be added to those variables, too ? Are there any use-case ?

So far I am only using the cloud top pressure (from these other cloud products).
