### ISSUE TITLE
The search for closest point is not efficient for regional MPAS domain.

### ISSUE THREAD

**Issue by byoung-joo** [NCAR/obs2mpas#9]
Jake found that it took _forever_ to do the kd-tree search for his regional MPAS domain, while it is very quick for global domain.

I guess we need to add additional test to filter out the ABI pixels out of the regional domain to make it efficient.

**Comment by byoung-joo** [comment]
See Jerahmie's regional filter code : https://github.com/jerahmie/grid_filter

This simple condition might help.
https://github.com/jerahmie/grid_filter/blob/main/src/lam_domain_filter.cpp#L54-L57

This bdy check totally makes sense.
https://github.com/jerahmie/grid_filter/blob/main/src/lam_domain_filter.cpp#L61-L62

**Comment by byoung-joo** [comment]
working in [feature/regional_mesh](https://github.com/byoung-joo/obs2model/tree/feature/regional_mesh)

* now it runs fast with a regional mesh.
* Need further detailed test/analysis.

**Comment by liujake** [comment]
@byoung-joo Thank you for quickly resolving this issue. I will give it a try with this feature branch.

**Comment by liujake** [comment]
I just tried it with 3.75km regional mesh. It produced a ioda file with ~831K pixels, comparable to the number of grid cells 877K. I guess this difference is due to the exclusion of boundary layer 6 and 7's cells. This is good to use, I think.

**Comment by byoung-joo** [comment]
Not directly related to this issue, but below I added two figures from Jake's regional mesh.

* mesh-based cloud fraction from ABI cloud mask
![mpas_cf](https://github.com/byoung-joo/obs2model/assets/33296274/44f91245-fde1-4284-9662-254e9b37d758)

* Number of obs used for superob
![mpas_so_number](https://github.com/byoung-joo/obs2model/assets/33296274/3a717901-a8b5-417a-b85c-d508f9a73ef6)
